"use client";

import Image from "next/image";


function isMobile() {


  const userAgent = navigator.userAgent || window.opera;
  return /android|iphone|ipad|ipod|blackberry|iemobile|opera mini/i.test(userAgent.toLowerCase());


}

const GradientButton = () => {

  // const handleClick = () => {
  //   window.location.href = 'https://www.baidu.com';
  // };

  return (


    <a href="https://apps.apple.com/us/app/floraltile/id6504483514" target="_blank" rel="noopener noreferrer">
      <button className="bg-gradient-to-r from-blue-300 via-purple-300 via-pink-300 via-orange-300 to-red-300 text-white font-bold py-4 px-5 rounded-full shadow-lg transform transition duration-300 hover:scale-105 mt-6 mb-6"
        target='_blank'
      >
        Download In iOS
      </button>
    </a>
  );
};

export default function Home() {


  // useEffect(() => {
  //   isMobile()
  // }, []);

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-12 bg-black">




      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex bg-red" >


        <Image
          className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert rounded-[20px]"
          src="/logo1.jpg"
          alt="pattern tile Logo"
          width={70}
          height={70}
          priority
        />

        {typeof window !== "undefined" && isMobile() ? <p className="relative text-white mt-2 text-2xl mt-[20px]">FloralTile</p> : <p className="relative text-white mt-2 text-2xl mr-[600px]">FloralTile</p>}

        {typeof window !== "undefined" && isMobile() ? <></> : <GradientButton />}




        {/* <button
          class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          onclick="window.location.href='https://www.baidu.com'">
          download
        </button> */}


      </div >

      <p className="text-white mt-2 mt-[30px]">Seamless tile patterns generated by AI, such as flowers, fruits, and small animals </p>


      <video
        className="w-full max-w-3xl rounded-lg shadow-lg"
        style={{ width: '280px' }}
        controls
      >
        <source src="/intro.mp4" type="video/mp4" />

        Your browser does not support the video tag.
      </video>


      {/* <div style={{ width: '20px', height: '20px' }}></div> */}
      <GradientButton />

      {/* <div style={{ width: '20px', height: '20px' }}></div> */}

      {
        !isMobile() ? <>
          <p className="text-white w-[700px] ">
            can be downloaded as single patterns or full screen patterns for any purpose. There are over 200 types of flower patterns, 80 types of fruits, 40 types of animal patterns, and 600 types of ceramic tile patterns, which are rich in variety and generate clear images. They can be used as wallpapers, murals, fabrics, and any other places you want to use.
          </p>


          <p className="text-transparent bg-clip-text mt-10 mb-5" style={{
            background: 'linear-gradient(to right, #a0bcf3, #b1afe9, #d7a2da, #e89ccb, #f5b8b0)', WebkitBackgroundClip: "text",
            color: "transparent"
          }}>
            20 Promo Codes for iOS
          </p>

          <p className="text-white w-[700px] ">FXM77EXR4XPY
            FN4LFYJ66M6E&nbsp;
            RFHHLYFWF9HX&nbsp;
            6R9P3WELA9NF&nbsp;
            AWX94TA4W6R7&nbsp;
            69T6PY9NHPRT&nbsp;
            ANTFKXFPJ4JM&nbsp;
            R9MEH6L7H7TX&nbsp;
            K9W4RXPWWWN6&nbsp;
            NK4993X3WXJJ&nbsp;
            XY7R6794XT66&nbsp;
            J3J7PELP3AHW&nbsp;
            AMPLT7F7AJ9F&nbsp;
            EYPPALT3FJ3N&nbsp;
            K66MYX4KJW9X&nbsp;
            HTRYT49KWJ3W&nbsp;
            MA6TW4EX3LW4&nbsp;
            TRTKKHRW9HTW&nbsp;
            NWX343NHJ93E&nbsp;
            NMW4JPWAMFJ3&nbsp;
          </p></> : <>
          <p className="text-white w-[350px]">
            can be downloaded as single patterns or full screen patterns for any purpose. There are over 200 types of flower patterns, 80 types of fruits, 40 types of animal patterns, and 600 types of ceramic tile patterns, which are rich in variety and generate clear images. They can be used as wallpapers, murals, fabrics, and any other places you want to use.
          </p>


          <p className="text-transparent bg-clip-text mt-10 mb-5" style={{
            background: 'linear-gradient(to right, #a0bcf3, #b1afe9, #d7a2da, #e89ccb, #f5b8b0)', WebkitBackgroundClip: "text",
            color: "transparent"
          }}>
            20 Promo Codes for iOS
          </p>

          <p className="text-white w-[350px] ">FXM77EXR4XPY
            FN4LFYJ66M6E&nbsp;
            RFHHLYFWF9HX&nbsp;
            6R9P3WELA9NF&nbsp;
            AWX94TA4W6R7&nbsp;
            69T6PY9NHPRT&nbsp;
            ANTFKXFPJ4JM&nbsp;
            R9MEH6L7H7TX&nbsp;
            K9W4RXPWWWN6&nbsp;
            NK4993X3WXJJ&nbsp;
            XY7R6794XT66&nbsp;
            J3J7PELP3AHW&nbsp;
            AMPLT7F7AJ9F&nbsp;
            EYPPALT3FJ3N&nbsp;
            K66MYX4KJW9X&nbsp;
            HTRYT49KWJ3W&nbsp;
            MA6TW4EX3LW4&nbsp;
            TRTKKHRW9HTW&nbsp;
            NWX343NHJ93E&nbsp;
            NMW4JPWAMFJ3&nbsp;
          </p>



        </>



      }




    </main >
  );
}
